spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3000


zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8080/
    user:
      path: /user/**
      url: http://localhost:8000/user

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8000/oauth/token
      userAuthorizationUri: http://localhost:8000/oauth/authorize
      clientId: ui1
      clientSecret: ui1-secret
    resource:
      userInfoUri: http://localhost:8000/user
      preferTokenInfo: false