spring:
  application:
    name: gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 3000




zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8080/resource
    user:
      path: /user/**
      url: http://localhost:8000/uaa/user

security:
  oauth2:
    client:
      clientId: ui1
      clientSecret: ui1-secret
      accessTokenUri: http://localhost:8000/uaa/oauth/token
      userAuthorizationUri: http://localhost:8000/uaa/oauth/authorize
      use-current-uri: false
    resource:
      userInfoUri: http://localhost:8000/uaa/user
      preferTokenInfo: false
debug: true
