spring:
  application:
    name: gateway
server:
  port: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    resource-server:
      path: /resource/**
      serviceId: resource-server
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8000/oauth/token
      userAuthorizationUri: http://localhost:8000/oauth/authorize
      clientId: test_client
      clientSecret: 123456
      lientAuthenticationScheme: form
#      use-current-uri: false
#      pre-established-redirect-uri: http://localhost:3000
#      registered-redirect-uri: http://localhost:3000
    resource:
      userInfoUri: http://localhost:8000/user
      preferTokenInfo: false
