spring:
  application:
    name: resource-server
  datasource:
    url: jdbc:mysql://192.168.4.209:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true